---
## 1) [Numpy Array Hackerrank Quiz](https://www.hackerrank.com/challenges/np-arrays/problem)

The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data.

To use the NumPy module, we need to import it using:
```python
import numpy
```

**→ Arrays**

A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.

```python
import numpy

a = numpy.array([1,2,3,4,5])
print a[1]          #2

b = numpy.array([1,2,3,4,5],float)
print b[1]          #2.0
```

In the above example, numpy.array() is used to convert a list into a NumPy array. The second argument (float) can be used to set the type of array elements.

**→ Task**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

**→ Input Format**

A single line of input containing space separated numbers.

**→ Output Format**

Print the reverse NumPy array with type float.

Sample Input: ```1 2 3 4 -8 -10```


Sample Output: ```[-10.  -8.   4.   3.   2.   1.]```

In [ ]:
import numpy as np

def arrays(arr):
  #arr listesinin uzunluğu boyunca dönmesi için for tanımlandı.
  for i in range(len(arr)):
    #Input'u float olarak değiştirelim.
    arr[i]=float(arr[i])
  #arr listesini tersine çevirmek için:
  arr = arr[::-1]
  return np.array(arr)

#Input'u al, boşluklarına göre ayır ve arr değişkenine ata:
arr = input().strip().split(' ')

#arrays fonksiyonunu çağıralım ve input olarak aldığımız arr değişkenini parametre olarak verelim
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


---
## 2) [Numpy Concatenate Hackerrank Quiz](https://www.hackerrank.com/challenges/np-concatenate/problem)

Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:

```python
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

print numpy.concatenate((array_1, array_2, array_3))    
```
```
#Output
[1 2 3 4 5 6 7 8 9]
```


If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it is along the first dimension.

```python
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print numpy.concatenate((array_1, array_2), axis = 1)   
```
```python
#Output
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]    
```

**→ Task**

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis.


**→ Input Format**

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

**→ Output Format**

Print the concatenated array of size X.

Sample Input
```
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4
```

Sample Output
```
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
``` 

In [4]:
import numpy as np
#Öncelikle ilk verilen input'u boşluklarla ayırarak 3 farklı değişkene atıyorum:
print("""İlk matrisin satır bilgisini, ikinci matrisin satır bilgisini ve iki
matrisin de sütun bilgisi olacak şekilde 3 değer giriniz:""")
a, b, c = map(int,input().split())
#a, b, c = 4, 3, 2

#4'e 2 ve 3'e 2 olacak şekilde np array'lerimi oluşturuyorum.Bu aşamada 4 ve 3
#defa input bilgisini isteyeceğim için range fonksiyonu ile for'a alıp kaç kere
#input gelmesi gerektiğini belirtiyorum. Ardından aldığım inputları split
#ederek 0 ve 1. sütunlara ait olarak ekliyorum:
print(f"\nİlk array'in sırasıyla 0 ve 1.sütunlarında alacak değerleri giriniz:")
arr1 = np.array([input().split() for _ in range(a)],int)
print(f"\nİkinci array'in sırasıyla 0 ve 1.sütunlarında alacak değerleri giriniz:")
arr2 = np.array([input().split() for _ in range(b)],int)

#Bahsettiğim şekilde oluşturduğum iki array'i concatenate ediyorum:
print(f"\nConcatenate edilmiş array: \n {np.concatenate((arr1, arr2), axis = 0)}")

İlk matrisin satır bilgisini, ikinci matrisin satır bilgisini ve iki
matrisin de sütun bilgisi olacak şekilde 3 değer giriniz:
4 3 2

İlk array'in sırasıyla 0 ve 1.sütunlarında alacak değerleri giriniz:
1 2
1 2
1 2
1 2

İkinci array'in sırasıyla 0 ve 1.sütunlarında alacak değerleri giriniz:
3 4
3 4
3 4

Concatenate edilmiş array: 
 [[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


---
## 3) [Numpy Min and Max](https://www.hackerrank.com/challenges/np-min-and-max/problem)

**→ Min**

The tool min returns the minimum value along a given axis.
```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]
print numpy.min(my_array, axis = None)      #Output : 0
print numpy.min(my_array)                   #Output : 0
```
By default, the axis value is None. Therefore, it finds the minimum over all the dimensions of the input array.

**→ Max**

The tool max returns the maximum value along a given axis.

```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]
print numpy.max(my_array, axis = None)      #Output : 7
print numpy.max(my_array)                   #Output : 7
```

By default, the axis value is None. Therefore, it finds the maximum over all the dimensions of the input array.

**→ Task**

You are given a 2-D array with dimensions X.
Your task is to perform the min function over axis  and then find the max of that.

**→ Input Format**

The first line of input contains the space separated values of  and .
The next  lines contains  space separated integers.

**→ Output Format**

Compute the min along axis  and then print the max of that result.

Sample Input
```
4 2
2 5
3 7
1 3
4 0
```

Sample Output
```
3
```

In [7]:
import numpy as np
"""
Bu sefer one line code ile bir çözüm gerçekleştirelim. Diğer çözümlerden farklı
olarak burada ilk input bir değişkene atanmak yerine direkt:

int(input().split()[0])

olarak alınmıştır. Bu bilgi bize nasıl bir array oluşturacağımız yani 
kullanıcıdan kaç kere daha input alacağımızı söyler. Dolayısıyla bunu for'a alarak
kullanıcıdan buradan gelen değer kadar daha input isteyeceğiz. Ardından aldığımız
değerleri split edeceğiz. Şu an buraya kadar geldik:

[input().split() for _ in range(int(input().split()[0]))]

Devamında artık elimizdeki bu değerler ile bir tipi int olan np.array oluşturacağız:

np.array([input().split() for _ in range(int(input().split()[0]))],int)

Son olarak önce axis=1'de min alıp ardından default olan axis=0'da max alacağız.
Kodumuzun son şeklini vermiş olacağız.
"""
print(f"Problem Sonucu: {np.max(np.min(np.array([input().split() for _ in range(int(input().split()[0]))],int),axis=1))}")

4 2
2 5
3 7
1 3
4 0
Problem Sonucu: 3


---
## 4) [Numpy Sum and Prod](https://www.hackerrank.com/challenges/np-sum-and-prod/problem)

**→ Sum**

The sum tool returns the sum of array elements over a given axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10
```

By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.

**→ Prod**

The prod tool returns the product of array elements over a given axis.

```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
```

By default, the axis value is None. Therefore, it performs the product over all the dimensions of the input array.

**→ Task**

You are given a 2-D array with dimensions X.
Your task is to perform the  tool over axis  and then find the  of that result.

**→ Input Format**

The first line of input contains space separated values of  and .
The next  lines contains  space separated integers.

**→ Output Format**

Compute the sum along axis . Then, print the product of that sum.

Sample Input
```
2 2
1 2
3 4
```

Sample Output
```
24
```

In [5]:
import numpy
#alınan input'un split edilip ardından int tipine map edilerek değişkenlere atanması:
print("Kaça kaçlık bir array olsun:")
N, M = map(int, input().split())

#N defa daha input alınıp split edilip ardından int tipinde bir numpy array oluşturulması:
print("Array'in bana sırasıyla değerlerini girer misin:")
A = numpy.array([input().split() for _ in range(N)],int)

#Oluşturduğumuz A array'inin axis=0'a göre elemanlarının toplamının yine
#axis=0'a göre çarpımını tek satırda alalım:
print(f"Sonuç: {numpy.prod(numpy.sum(A, axis=0), axis=0)}")

Kaça kaçlık bir array olsun:
2 2
Array'in bana sırasıyla değerlerini girer misin:
1 2
3 4
Sonuç: 24
